name: Validate code in the merge queue

on:
  merge_group:
    paths:
      - "src/**"
      - "static/**"
      - "svelte.config.js"
      - "tailwind.config.js"
      - "vite.config.ts"
      - ".github/workflows/**"

  pull_request:
    paths:
      - "src/**"
      - "static/**"
      - "svelte.config.js"
      - "tailwind.config.js"
      - "vite.config.ts"
      - ".github/workflows/**"

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: |
          npm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          # this should match the `pages` option in your adapter-static options
          path: "build/"
